# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170624_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comments',
            field=models.BooleanField(default=False),
        ),
    ]
